version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  pgsql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tic_tac_toe
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: tic_tac_toe
  api:
    build:
      context: ./services/api
      dockerfile: ../../docker/api/Dockerfile
    volumes:
      - ./services/api:/usr/src/app
    ports:
      - '12321:12321'
    entrypoint:
      - npm run db migrate:latest
      - npm run start
    depends_on:
      - redis
      - postgres
  proxy:
    build:
      context: ./services/client
      dockerfile: ../../docker/proxy/Dockerfile
    entrypoint:
      - nginx restart
    depends_on:
      - pgsql
      - redis
      - api
