auth_enabled: false

server:
  http_listen_address: "0.0.0.0"
  http_listen_port: 3100

ingester:
  lifecycler:
    address: "127.0.0.1"
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /var/loki/wal

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /var/loki/index

  filesystem:
    directory: /var/loki/chunks
