name: Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          git submodule init
          git submodule sync
          git submodule update
          echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin
          docker build -f ./docker/api/Dockerfile -t alexanderfromearth/tic-tac-toe-api:latest ./services/api
          docker push alexanderfromearth/tic-tac-toe-api:latest
          cd ../
          docker build -f ../docker/proxy/Dockerfile -t alexanderfromearth/tic-tac-toe-proxy:latest .
          docker push alexanderfromearth/tic-tac-toe-proxy:latest
      - run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tControlMaster auto\n\tControlPersist 10m\n\tControlPath ~/.ssh/%r@%h:%p" > ~/.ssh/config
          echo "${{ secrets.USER }}@${{ secrets.HOST }}"
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -T -i ~/.ssh/id_rsa "${{ secrets.USER }}@${{ secrets.HOST }}" << EOL
            cd /var/www/tic-tac-toe
            git pull
            git submodule init
            git submodule sync
            git submodule update
            sudo su
            docker-compose pull
            docker-compose up -d
          EOL
