name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Docker login
        run: |
          echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin
      - name: Build backend
        run: |
          docker build -f ./docker/api/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe-api:latest ./services/api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe-api:latest
      - name: Build frontend
        run: |
          docker build -f ./docker/proxy/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe-frontend:latest ./services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe-frontend:latest
      - name: Build proxy
        run: |
          docker build -f ./docker/proxy/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe-proxy:latest ./services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe-proxy:latest
      - name: Deploy on Node
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tControlMaster auto\n\tControlPersist 10m\n\tControlPath ~/.ssh/%r@%h:%p" > ~/.ssh/config
          echo "${{ secrets.USER }}@${{ secrets.HOST }}"
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -T -i ~/.ssh/id_rsa "${{ secrets.USER }}@${{ secrets.HOST }}" << EOL
            cd /var/www/tic-tac-toe
            git pull
            git submodule init
            git submodule sync
            git submodule update
            sudo su
            docker-compose pull
            docker-compose up -d
          EOL
